language: node_js
node_js:
- 10.15.3
script: 'true'
deploy:
  provider: heroku
  api_key:
    secure: JaSjU9HXKcyOfca7cTpujRW6NDFPkbXzWspNdsQB7TATv9SSN2VlVSY2xWGl0hzj1eJ3xTm/RNp6prhYVLnb9EgWWL9BHsRBY6m49QGLAg5OE1iPDyyUaphPHWvC3ry/vzmia28LU/gM82jMu9cWiVJBhCG8YWPOHQM2ycF3fVqsPt/698dzy65XrKkJaIFhp6aSiEL3YhHW2/wwejf/r6u8io+LPrqidtfv20hpae9WR7KLZvMEZGQH40cE4HAAOS7bV/BLIcLAkw8NbPF6ASt1nJpXVfUDFQYr5O8F+kIq/fc2BVd12wasqrnREVEZlBP83WOODe2t/QyoCXl1xCi8R6a/R6lrFR3su2iHETPjd41hBiegmf9bHxXyMzuk+9awZu1Oq8Jl9OM1p3V+3uyBQtw3xPyYHAkouFw2RTo44GUOL0HrWzwuuW2y10MX5ABpDQ1SVY0L8dSg/cG6BPg7HFFecwl5P4oXdTlzn4Jvd+Qo+sXLrP8sCwRC823ixWn+wdc2WGt4cM0sN/UGOEzkautgPGBjYXRy5NUaLamXnjgSEaeerY1bf1/+e8meoaEh0i7Xmd9cAdbHBGJT38nhabOgwBQ2NIBNDNRbxtnt0wC3Zh98tqNP0BvDPf8dUhCY7SPzvI3A0yFobJX0ROKGNYPCl+7Y/tu7duRk0ME=
  app: rsoi-lab1-ci
  on:
    repo: EgorFlamingo/rsoi-lab1-ci
env:
  global:
    
