language: node_js
node_js:
- 10.15.3
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: NZWC0aKdKEvcrjfEWEStgQnzQIqNscDBAUV4kbFbH0QYzgBu9rquQQdqesTa+XLKrtfhSj5/2qB78N+llorBxCYLqVTEyGIg3GlROZecwjh0YiigaREE5ry3S3+yeVjbCtUIIb08w+QQJQt0x4KM/dLAQy+ai/FOPaBtR86Q9bFLrnsSvM48/Stf8GsYbPBpxRKoB4T28dDyS+Cmd+xEDqqJIuJyvJaAzrjtS8UADcLvFwO/77vJdKjP5Fip38KkPvzgxBj6oJXL7wKxH9FEdX3a4tyqJT8xqeifpKa1NNK53Z7XiGsb9eTHhoMq4shuekUuCEkLyEeeduYPNqdPud4pFR3z/F63S9RVCplKF067bek8r8FCl9GsPsoZ4sNrnkTOYNHgk8eNXrnVkOLbz5SoG1cnt8+1cX1uPbe1AEvrppmLXM5NQ5xsQUW1jNvcBabBtdbxaUng4QVOb9sEHNbzqJl9BDDcJPmWPxliE0GdVzxVQL1I1unr9SI4eDrpzXSOLgnCQNqiN9ZBrDyKcuFfKpTBA3ncq+aPn+6Xf6uIWxAXaMR74iKBteZgHF9fyXlXo6Q+kAo5VAXkrNd5shSlglNxClOKFnG+XqUan54EWAeXM7sbYORF/CuD7EVGD2xm1M6R3qBBBxq/uLRTqfJ7ZDS2J8axDh2rYaIrsTw=
  app: rsoi-lab1-ci
  on:
    repo: EgorFlamingo/rsoi-lab1-ci